<<<<<<< HEAD
language: php
php:
 -5.5
 -5.6
 before_script:
 -composer self-update
 -composer install
script:
 phpunit Test.php
=======
language: php
php:
  - 5.5
  - 5.6
 before_script:
  - composer self-update
  - composer install
script:
  phpunit Test.php
>>>>>>> origin/master
